version: '3'
services:
    forms:
        build: .
        image: earthdata-pub-forms
        environment: 
            API_ROOT: "localhost:8080"
            DASHBOARD_ROOT: "localhost:3000"
            OVERVIEW_ROOT: "/"
        ports:
            - "8081:8080"
        tty: true
