# Created using the following reference:
#   https://docs.github.com/en/actions/using-workflows/about-workflows

name: github-actions
run-name: Deploy to ${{ github.head_ref || github.ref_name }}  by @${{ github.actor }}
on: [push]
jobs:
  test-snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.EDPUB_SNYK_TOKEN }}
        with:
          args: "--all-projects --detection-depth=6  --org=edpub --severity-threshold=high"